openapi: 3.0.0
info:
  title: Ben Test API
  version: 0.0.1
  description: Simple API to demo the API Builder in Postman
  contact:
    name: Ben Coughlan
    email: bencoughlan@hotmail.co.uk
servers:
  - url: http://localhost:3000
    description: Test files API
paths:
  /files/all:
    get:
      operationId: allFiles
      summary: List all videos
      description: Returns a list of all the files
      tags:
        - files
      responses:
        '200':
          description: List of videos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/files"
  /files/{fileId}:
    get:
      operationId: oneFiles
      summary: Fetch one file by ID 
      description: Retrieve information for specific file
      tags:
        - files
      parameters:
      - name: fileId
        in: path
        required: true
        schema:
          type: number
          example: 4

      responses:
        '200':
          description: List of files
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/file"

components:
  schemas:
    video:
      type: object
      properties:
        name:
          type: string
          description: File title
          example: "Public Workspaces"
        url:
          type: string
          description: Files URL
          example: "test.pdf"
        views:
          type: number
          description: File sizes
          example: 7482

tags:
  - name: files
    description: API returning info about files