openapi: 3.0.0
info:
  title: Production Workflow API
  version: 0.0.1
  description: API for Integrations with Hogarth Production
  contact:
    name: Ben Coughlan
    email: ben.coughlan@hogarthww.com
servers:
  - url: http://localhost:3000
    description: Test API
paths:
  /pwapi/all:
    get:
      operationId: getRecentFolderCreation
      summary: List last 24 Hour of Folder Creation
      description: Returns a list of all the processed folder creation jobs
      tags:
        - files
      responses:
        '200':
          description: List of videos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/files"
  /pwapi/new:
    post:
      operationId: oneFiles
      summary: Fetch one file by ID 
      description: Retrieve information for specific file
      tags:
        - files
      parameters:
      - name: new
        in: path
        required: true
        schema:
          type: number
          example: 4

      responses:
        '200':
          description: List of files
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/file"

components:
  schemas:
    video:
      type: object
      properties:
        name:
          type: string
          description: File title
          example: "The Public Workspaces"
        url:
          type: string
          description: Files URL
          example: "test.pdf"
        views:
          type: number
          description: File sizes
          example: 7482

tags:
  - name: files
    description: API returning info about files